name: Go Build and Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: read repo
        uses: actions/checkout@v4

      - name: init 
        # uses: actions/checkout@v2
        run: |
          go mod init blog
          go mod tidy
          go build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./main.exe
