name: Go Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: go mod init blog
        run: go mod init blog

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -o myapp ./...

      - name: Deploy
        run: |
          echo "Deploying..."
