on: push
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Check Node.js version
        run: node --version
      - name: Test
        run: echo "Running tests..."
      - name: init go
        run: go mod init myapp
      - name: download dependency
        run: go mod tidy
      - name: build
        run: go build -o myapp
      - name: deploy
        run: echo "Deploying"
