name: Go Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: deploy
        # uses: actions/checkout@v2
        run: |
          go mod init blog
          go mod tidy
          go build

